version: '3.8'
services:

  frontend-desktop:
    depends_on:
      - spring-backend
    build: ./desktop-app
    image: mamouros99/desktop
    container_name: dektop_c
    ports:
      - '8081:80'
    volumes:
      - ./lh-nginx.conf:/etc/nginx/nginx.conf  

  frontend-mobile:
    depends_on:
      - spring-backend
    build: "./mobile-app"
    image: mamouros99/mobile
    container_name: mobile_c
    ports:
      - '8080:80'
    volumes:
      - ./lh-nginx.conf:/etc/nginx/nginx.conf

  spring-backend:
    depends_on:
      - mysqldb
    build: ./backend
    image: mamouros99/backend
    container_name: spring_c
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "server.port" : $SPRING_DOCKER_PORT,
        "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver"}'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  mysqldb:
    image: mysql:8.0.33
    restart: unless-stopped
    container_name: ist_mysql_c
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
volumes:
  db:

